# Generated by Django 5.1 on 2024-08-23 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='CRF_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_alias', models.TextField()),
                ('link_description', models.TextField()),
                ('link_location', models.URLField()),
                ('base_url', models.URLField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account')),
            ],
            options={
                'verbose_name': 'CRF Document',
                'verbose_name_plural': 'CRF Documents',
            },
        ),
        migrations.CreateModel(
            name='CRF_Validation_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_alias_match', models.JSONField()),
                ('link_url_match', models.JSONField()),
                ('pass_validation', models.BooleanField(default=False)),
                ('crf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.crf_document')),
            ],
            options={
                'verbose_name': 'CRF Validation Result',
                'verbose_name_plural': 'CRF Validation Results',
            },
        ),
    ]
